name: SILShack Spring 2016
pygments: true
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough"]

timezone: America/New_York

special-categories: 
  - "exercise"
  - "how-to"

# These can contain uppercase: they'll be lowercased in the URL
page-order:
  - syllabus
  - schedule
  - exercises
  - how-to
  - people
  - feedback

# Same note RE case above
python-extra-pages:
  - console
  
  
baseurl: /spring2016
url: /spring2016

python: true

course:
  title: Programming for Information Professionals
  number: INLS 560
  instructor: Prof. Elliott Hauser
  semester: Spring 2016

authors:
  elliott:
      name: Elliott Hauser
      prof: true
      gravatar: 0d0d432948d262195358f339768f1240
      website: http://www.elliotthauser.com
      github: eah13
      twitter: hauspoor
      about:  Elliott Hauser is a PhD Student in information science at UNC Chapel Hill.  He's hacking education as one of the cofounders of Trinket.io.  
